services:
  - type: web
    name: website
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn website.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: SECRET_KEY
        generateValue: true