databases:
  - name: dachosendb
    databaseName: website
    user: dachosenwong
    plan: free

services:
  - type: web
    name: website
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn website.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dachosendb
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: SECRET_KEY
        generateValue: true