services:
  - type: web
    name: website
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn website.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true