# Generated by Django 4.0.4 on 2022-04-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('portion_yield', models.PositiveSmallIntegerField()),
                ('creation_stamp', models.DateTimeField(auto_now_add=True)),
                ('update_stamp', models.DateTimeField(auto_now=True)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('recipes', models.ManyToManyField(to='recipes.recipe')),
            ],
        ),
    ]
